### ISSUE TITLE
Game Freezes

### ISSUE THREAD

**Issue by dfolz** [rsk2327/NEAT_FlappyBird#1]
When I run testBird.py, The Flappy Bird game window appears, but the game freezes so I cannot see the game being played by the machine. 

I also get this warning message:
libpng warning: iCCP: known incorrect sRGB profile

Any tips to fix this issue?

**Comment by rsk2327** [comment]
The code would require some modifications to run properly in different systems. There are a lot of places where I am referring to locations in my computer. So you would have to change that before the code can run properly.

Anywhere that you see '/home/roshan/Documents' , you should replace it with your own directory path

`
BACKGROUND = pygame.image.load('/home/roshan/Documents/FlappyBird/background.png')

class Bird(pygame.sprite.Sprite):
    def __init__(self,displayScreen):
        pygame.sprite.Sprite.__init__(self)
        self.image = pygame.image.load('/home/roshan/Documents/FlappyBird/redbird.png')
`
