### ISSUE TITLE
module neat has no attribute Config

### ISSUE THREAD

**Issue by adibyte95** [rsk2327/NEAT_FlappyBird#2]
this is the error on running flappyBird3.py python file

**Comment by rsk2327** [comment]
The NEAT algorithm is implemented by the NEAT-Python package. Install the package using `sudo pip install neat-python`. Ensure that this package is installed before running any of the files.

**Comment by LayanCS** [comment]
> The NEAT algorithm is implemented by the NEAT-Python package. Install the package using `sudo pip install neat-python`. Ensure that this package is installed before running any of the files.

Didn't help

**Comment by LayanCS** [comment]
It worked when I tried `pip install neat-python==0.9` (the most recent version). You need to be specifying the version in order to get the most recent one, otherwise you won't get it.

**Comment by adibyte95** [comment]
as per @LayanCS  comment i am closing the issue....

**Comment by ThisMonkeysGoneToHeaven** [comment]
I just uninstalled the neat-python package and reinstalled it again. It worked for me.

**Comment by ghost** [comment]
pip install neat-python==0.92 fixed it for me.

**Comment by NathanDai5287** [comment]
I did:
`pip uninstall neat`
`pip install neat-python`
