### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ZZcat** [rsk2327/NEAT_FlappyBird#3]
I'm getting an error from testbird.py.  What version of neat does this program use?

Python 2.7.14 error:
`Traceback (most recent call last):
  File "/Users/zachz/Downloads/neuroevolution-for-flappy-birds-master/testBird.py", line 262, in <module>
    config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction,
AttributeError: 'module' object has no attribute 'Config'`

Python 3.6.5 error:
`''Traceback (most recent call last):
  File "/Users/zachz/Downloads/neuroevolution-for-flappy-birds-master/testBird.py", line 262, in <module>
    config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction,
AttributeError: module 'neat' has no attribute 'Config'`

**Comment by rsk2327** [comment]
The code requires the NEAT-Python package to function. It can be installed using 
`sudo pip install neat-python`. Ensure that its installed before running any of the codes.

Also, you need a trained model before you can use the testBird.py file. So run flappyBird3.py first, train a model, and then use the testBird.py file.
